codecov:
  branch: main

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      go:
        target: 100%
        threshold: 0%
        informational: false
        flags:
          - go
    patch: off

comment:
  layout: "reach, diff, files"
  require_changes: false

fixes:
  - "github.com/pg83/kv/::"

ignore:
  - "tst/**/*"
  - "dev/**/*"
